### ISSUE TITLE
Using this package to control TDC001 servo on mac mac OS Sierra 10.12

### ISSUE THREAD

**Issue by NotSoShaby** [UniNE-CHYN/thorpy#11]
Hey, 
I'm trying to control my thorlabs TDC001 servo from python on mac OS Sierra 10.12 OS. 
All my trials so far resulted in errors. Can someone please explain how would I go about doing this/is this package what i'm looking for? 
The ReadMe file didn't help a lot in answering my questions.

**Comment by lfasnacht** [comment]
Hey,

Can you give me some more details about the errors you experience?

Unfortunately I don't have much experience on Mac OS, I guess you may have to do some adaptation on the stage discovery :
https://github.com/UniNE-CHYN/thorpy/blob/a835090645273ccdef6d6537ac6b0a795fa475fb/thorpy/comm/discovery.py#L20-L23

Let me know!

**Comment by NotSoShaby** [comment]
I get the NotImplementedError in the code you described. 
my platform.system() is "Darwin" .
![image](https://user-images.githubusercontent.com/26500236/33324779-38c9b7d4-d459-11e7-9a04-7d6aea2a3836.png)

Skipping that if statement results in this error:
![image](https://user-images.githubusercontent.com/26500236/33324802-4da2e568-d459-11e7-8f47-07069a8fe5c3.png)

**Comment by lfasnacht** [comment]
Well, I don't know how to do the discovery in Mac OS (and unfortunately I don't have a Mac nearby). You could try simply skipping all these lines and directly initializing the `Port` with the correct port name (on Mac OS I think it's something like `/dev/tty...`). (lines 27-29)

**Comment by NotSoShaby** [comment]
Hey, 
Could you possibly expand on the following two lines of code (what each does)?
```

port_candidates = [x[0] for x in serial_ports if x[2].get('SER', None) == dev.serial_number] 

serial_ports = [(x[0], x[1], dict(y.split('=', 1) for y in x[2].split(' ') if '=' in y)) for x in comports()]
```

This will help me solve this problem. 
Of course I'll post the solution once I have it

**Comment by NotSoShaby** [comment]
Also, I would love to know what this `Port.create` method is expecting to get as the first param (port). 
I'm trying to get that param using a different tool but I'm not sure what it is expecting me to pass to it. 
`p = Port.create(port, dev.serial_number)`

**Comment by lfasnacht** [comment]
Hi,
Sorry for the delay.

The second line transforms the output of `serial.tools.list_ports.comports()` into something more practical. Each element of the return of this function is an iterable which contains 3 elements:

```python
['/dev/ttyUSB0',
 'APT DC Motor Controller',
 'USB VID:PID=0403:FAF0 SER=83856xxx LOCATION=1-4']```

It keeps the two first without touching them, and modifies the third one to be a dictionary. The result is stored in `serial_ports`:

```python
>>> print(serial_ports)
[('/dev/ttyUSB0', 'APT DC Motor Controller', {'VID:PID': '0403:FAF0', 'LOCATION': '1-4', 'SER': '83856xxx'})]
```

The first line tries to match the serial number of the serial port device with the serial number of the USB device.

It looks at each entry, and checks if the third element of the tuple (which is a dictionary) matches the serial number of the usb device and returns the first element of the tuple (the serial port device name).

To answer your second question, I would suggest to try something like this in a python shell:

```python
>>> from serial.tools.list_ports import comports
>>> from thorpy.comm.port import Port
>>> [x[0] for x in comports()]
['/dev/ttyUSB0']
>>> x=Port.create('/dev/ttyUSB0','1234')
```

If it works, you should get some output...

**Comment by lfasnacht** [comment]
Closed (no feedback for two month... please re-open if needed)
