### ISSUE TITLE
home() can only be issued once.

### ISSUE THREAD

**Issue by PawelDefee** [UniNE-CHYN/thorpy#3]
While the normal use case is that home() is issued upon powerup of the stage and then the stage permanently displays 'homed' status, it would be good if home() would work afterwards as well. For this, instead of inspecting the 'homed' status, the code should await the MGMSG_MOT_MOVE_HOMED message.

**Comment by lfasnacht** [comment]
It's by design (but feel free to explain why I'm wrong, i.e. why a stage can have the 'homed' status that we should not care about):

Homing of a stage should be done once to initialize an "absolute" reference position. Afterwards you can just move it to position 0.

**Comment by PawelDefee** [comment]
Right, I am fine with this - I thought that maybe under heavy loads the stage would need to be 're-homed' every now and then, but I lack concrete evidence We'll see :)
