### ISSUE TITLE
How to fix usb permissions

### ISSUE THREAD

**Issue by mabl** [UniNE-CHYN/thorpy#5]
Hi,

I'm running into troubles with USB permissions when calling discover_stages(), since the iManufacturer keyword is not accessible as a normal user (same issue when I run lsusb as a user).  

Do you use any fancy udev rule to get access to these attributes?

Best,
mabl

**Comment by mabl** [comment]
The same holds for the serial number obviously

**Comment by lfasnacht** [comment]
Hi!

Let me know if this works for you?

You should make sure that you use the latest version, or at least apply commit 538c3f1, otherwise it may not work.

Best,
Laurent
